source 'https://rubygems.org'

	gem 'coffee-rails'
	gem 'ember-emblem-template'
	gem 'ember-rails'
	gem 'ember-source'
	gem 'emblem-rails'
	gem 'jbuilder'
	gem 'jquery-rails'
	gem 'pg'
	gem 'rails', '4.2.6'
	gem 'sass-rails'
	gem 'spring'
	gem 'uglifier'
